wait(120)
game:GetService("ReplicatedStorage").Remotes.Shop.ClientBuyGameItem:FireServer("GasTank", 1)
        wait(120)
        game:GetService("ReplicatedStorage").Remotes.Shop.ClientBuyGameItem:FireServer("GasTank", 2)
        wait(120)
        game:GetService("ReplicatedStorage").Remotes.Shop.ClientBuyGameItem:FireServer("GasTank", 3)
        wait(120)
        game:GetService("ReplicatedStorage").Remotes.Shop.ClientBuyGameItem:FireServer("GasTank", 4)
        wait(120)
        game:GetService("ReplicatedStorage").Remotes.Shop.ClientBuyGameItem:FireServer("GasTank", 5)
        wait(120)
        game:GetService("ReplicatedStorage").Remotes.Shop.ClientBuyGameItem:FireServer("GasTank", 6)
        wait(120)
        game:GetService("ReplicatedStorage").Remotes.Shop.ClientBuyGameItem:FireServer("GasTank", 7)
wait(120)

game:GetService("ReplicatedStorage").Remotes.Shop.ClientBuyGameItem:FireServer("GasTank", 8)
wait(120)

game:GetService("ReplicatedStorage").Remotes.Shop.ClientBuyGameItem:FireServer("GasTank", 9)