{
  "Generales/Tools":{
    "Status":true,
    "Url":"https://raw.githubusercontent.com/AnonyProArg/ScriptsRobloz/main/OneCreatorX%203.lua"
  },
  "12398414727":{
    "Status":true,
    "Url":"https://raw.githubusercontent.com/AnonyProArg/ScriptsRobloz/main/Math%20answer.lua"
  }
}
