{
  "Generales/Tools":{
    "Status":true,
"Url":"https://raw.githubusercontent.com/AnonyProArg/ScriptsRobloz/main/OneCreatorX%203.lua"
  },
  "12398414727":{
    "Status":true,
"Url":"https://raw.githubusercontent.com/AnonyProArg/ScriptsRobloz/main/Math%20answer.lua"
  },
 "13276475159":{
    "Status":true,
"Url":"https://raw.githubusercontent.com/AnonyProArg/ScriptsRobloz/main/CoffeShop.lua"
  },
 "6305942109":{
    "Status":true"
"Url":"https://raw.githubusercontent.com/AnonyProArg/ScriptsRobloz/main/Pasteler%C3%ADa/LaundryExe.lua"
  },
 "10108131074":{
    "Status":true,
"Url":"https://raw.githubusercontent.com/AnonyProArg/ScriptsRobloz/main/EjecuteAllCespet.lua"
  },
 "6915291292":{
    "Status":true,
"Url":"https://raw.githubusercontent.com/AnonyProArg/ScriptsRobloz/main/Pasteler%C3%ADa/ExePanaderia.lua"
  },
 "370731277":{
    "Status":true,
"Url":"https://raw.githubusercontent.com/AnonyProArg/ScriptsRobloz/main/Exes/MeepCity.lua"
  },
 "12398414727":{
    "Status":true,
"Url":"https://raw.githubusercontent.com/AnonyProArg/ScriptsRobloz/main/Math%20answer.lua"
  }
